### ISSUE TITLE
is this still maintained ?

### ISSUE THREAD

**Issue by ghost** [shirriff/bitcoin-code#2]
is the code still valid and maintained ?

i mean does it gives correct output of 

keyUtils.privateKeyToWif
keyUtils.keyToAddr

**Comment by jeffrade** [comment]
Looks like [this person](https://bitcoin.stackexchange.com/a/48395) got it working on Linux.

**Comment by shirriff** [comment]
Sorry, I'm not maintaining this code. It's not meant as a library for people to use.
